apiVersion: v1
kind: ReplicationController
metadata:
  name: webapitest-rc
  labels:
    name: webapitest-rc
spec:
  replicas: 3
  selector:  
    name: webapitest
  template:
    metadata:
      labels:
        name: webapitest
    spec:
      containers:
        - name: webapitest-container
          image: k8reg.azurecr.io/webapitest:1.0.0
          ports:
            - containerPort: 80
