---
apiVersion: v1
kind: Pod
metadata:
  name: webapitest
  labels:
    app: webapitest
spec:
  containers:
    - name: webapitest-container
      image: k8reg.azurecr.io/webapitest:1.0.0
      ports:
        - containerPort: 80
